### ISSUE TITLE
Whete can I find "mysecrete"?

### ISSUE THREAD

**Issue by Gopichandar** [zerodha/dotnetkiteconnect#29]
In the sample, 
User user = kite.GenerateSession(RequestToken, MySecret);

I have signup in https://developers.kite.trade/apps but cant find "MySecrete". 

Can you clarify where to find this?

**Comment by ajinasokan** [comment]
Right below your "API key" there is a button "Show API secret"

**Comment by Gopichandar** [comment]
Can you point out where? #
![Screenshot_20210304-110329~2](https://user-images.githubusercontent.com/13073344/109916400-92f1ce00-7cd9-11eb-935a-db3aba6d5d94.png)

**Comment by ajinasokan** [comment]
Could you post this in the [forum](https://kite.trade/forum/)? We can continue discussion there. Because this looks like an account related issue and not related to library.
