### ISSUE TITLE
Error while connecting. Message: The server returned status code '400' when status code '101' was expected

### ISSUE THREAD

**Issue by maulikshah88** [zerodha/dotnetkiteconnect#30]
ticker not working getting error "Error while connecting. Message: The server returned status code '400' when status code '101' was expected"

**Comment by ajinasokan** [comment]
Could you try enabling `Debug` in the Ticker constructor? It will give a detailed debug log. Paste here redacting authentication details.

**Comment by maulikshah88** [comment]
Hi, It was resolved later. a
