### ISSUE TITLE
utils.cs

### ISSUE THREAD

**Issue by m7010621123** [zerodha/dotnetkiteconnect#32]
i am using visual studio 2022. I use .NET Framework 4.8. But in Utils.cs , NotVisualBasic.FileIO and System.Text.Json both are missing. How can i resolve this issue?

**Comment by ajinasokan** [comment]
How was the library added? Was it using nuget ([like this](https://github.com/zerodha/dotnetkiteconnect#using-nuget))? If not try with that.

Alternatively you could try cloning this repo, open Sample project and run it after removing unwanted code from it to see if it works with your setup.
