### ISSUE TITLE
Code for Request Token

### ISSUE THREAD

**Issue by m7010621123** [zerodha/dotnetkiteconnect#33]
Can I have code for getting RequestToken programmatically. It is not available in Python API too. 

Why it is not there?

When i try to get the RequestToken , I receive "405" Error Code.,

**Comment by ajinasokan** [comment]
Could you expand on what you are exactly trying to achieve? Code sample (mask credentials)?

Also if this is not specific to this library or not a bug then the most appropriate place to ask help is [Kite Trade Forum](https://kite.trade/forum/).
