### ISSUE TITLE
GetHistoricalData failing due to integer overflow

### ISSUE THREAD

**Issue by sanchitabrol** [zerodha/dotnetkiteconnect#34]
While fetching Daily data for NSE:GLTINFRA (3518721), [this conversion](https://github.com/zerodha/dotnetkiteconnect/blob/eb6304bc5c51d5cc450c3e4d00fc5227a621331a/KiteConnect/Structures.cs#L69) is failing since Volume is 6161122183 on 2020-07-13 which is greater that `UInt32.MaxValue`. You probably need to change the contract to accommodate larger values.

https://github.com/zerodha/dotnetkiteconnect/blob/eb6304bc5c51d5cc450c3e4d00fc5227a621331a/KiteConnect/Structures.cs#L69

**Comment by ajinasokan** [comment]
Yes. This should be UInt64. I will patch and release as 4.0.0-pre.

**Comment by ajinasokan** [comment]
Will be available after validation. https://www.nuget.org/packages/Tech.Zerodha.KiteConnect/4.0.0-pre
