### ISSUE TITLE
Issue is with GetHistoricalData()

### ISSUE THREAD

**Issue by nitignaraval** [zerodha/dotnetkiteconnect#35]
[Instrument](url) Token: 3901185
From Date: 2015-12-22
To Date: 2016-03-21
OI: false

Contonuous: false
Error Message: System.OverflowException: 'Value was either too large or too small for a UInt32.'

![vs-ss](https://user-images.githubusercontent.com/22911984/188686611-31fb6731-c9e7-4dbe-a5d5-fd27ccacc485.png)

**Comment by ajinasokan** [comment]
This is patched in 4.0.0-pre. Refer: #34
