### ISSUE TITLE
Update Client Implementation

### ISSUE THREAD

**Issue by adaptyinsite-git** [zerodha/dotnetkiteconnect#36]
The WebRequest / HttpWebRequest used in Kite.cs are deprecated and do not work reliably on Linux systems. Please move to the recommended HttpClient.

See note from Microsoft at: https://learn.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest?view=net-7.0

**Comment by ajinasokan** [comment]
Will check this. Thanks for the heads up!

**Comment by ajinasokan** [comment]
Available in v4.3.0
