### ISSUE TITLE
No clear documentation for .net

### ISSUE THREAD

**Issue by sivakumargnair** [zerodha/dotnetkiteconnect#37]
there is no clear documentation on how to access API using .net. I have created an application in kiteconnect and its showing only API key, there is no API secret. As per documentation I need API secret. Why don't you include a working snippet for .net login

**Comment by ajinasokan** [comment]
In Kite Connect developer portal, go to your app details page. Below API key there will be a button `Show API secret`, click on it to see the app secret. Checkout the [sample app project](https://github.com/zerodha/dotnetkiteconnect/blob/master/KiteConnectSample/Program.cs#L453) to know basic use of this library.

Also make sure you have created a "Connect" type app. The "Publisher" type doesn't have API access and so no API secret.

For further queries and general API related help, join [Kite Connect developer forum](https://kite.trade/forum/). GitHub issues is meant for .Net client specific bugs and contributions.
