### ISSUE TITLE
Don’t we need a checksum property for the Order Payload?

### ISSUE THREAD

**Issue by tsh03** [zerodha/dotnetkiteconnect#38]
![image](https://github.com/zerodha/dotnetkiteconnect/assets/27768854/8a0cb023-3b62-4808-a98c-9a29e4c5b61c)

**Comment by ajinasokan** [comment]
Checksum is only available for order post back payloads. For order payloads your request is already authenticated with `access_token` which is generated with a similar checksum when you [login](https://kite.trade/docs/connect/v3/user/).
And all the requests to KiteConnect is via HTTPS, so they are end to end encrypted and can't be tampered.

**Comment by tsh03** [comment]
Got it. Thanks!
