### ISSUE TITLE
Use  HttpClient instead of WebRequest

### ISSUE THREAD

**Issue by saivineeth100** [zerodha/dotnetkiteconnect#39]
As per [Docs](https://learn.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated), [WebRequest](https://learn.microsoft.com/en-us/dotnet/api/system.net.webrequest) is deprecated and not recommended for developmemt
![image](https://github.com/zerodha/dotnetkiteconnect/assets/64919520/5e1201d2-cd23-4805-947e-94e411f09e00)

Effected method - https://github.com/zerodha/dotnetkiteconnect/blob/master/KiteConnect/Kite.cs#L1249

**Comment by saivineeth100** [comment]
Duplicate of #36

**Comment by ajinasokan** [comment]
Available in v4.3.0
